name: CI/CD Pipeline

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install npm dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Tests (Optional - will skip if no tests are defined)
      - name: Run Tests
        run: npm test || echo "No tests defined"

      # Step 5: Log in to DockerHub using GitHub Secrets
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build Docker Image and tag it
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app .

      # Step 7: Push Docker Image to DockerHub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app
